server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  h2:
    console:
      enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/travelMaker?serverTimezone=Asia/Seoul
    url: jdbc:mysql://121.178.106.179:3306/travelMaker?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
  redis:
    host: localhost
    port: 6379

  sql:
    init:
      mode: always
jwt:
  app:
    jwtSecretKey: ${JWT_APP_JWTSECRETKEY}


kakao:
  token-uri: https://kauth.kakao.com/oauth/token
  user-info-uri: https://kapi.kakao.com/v2/user/me
  grant-type: authorization_code

  client-id: ${KAKAO_CLIENT_ID} #login-test-TEST : 프로필 미선택
  redirect-url: http://localhost:8080/auth/kakao #login-test-TEST : 프로필 미선택